name: Test
on:
  workflow_dispatch:

jobs:
  edit:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps: &buildsteps

      - name: Actions/Checkout
        uses: actions/checkout@main

      - name: test and debugs
        run: |
          ls -la
          pwd
          gh --version
          git remote -v
          echo "Set new repo origin url"
          echo $GH_TOKEN
          git remote set-url origin https://$GH_TOKEN@github.com/Ariouz/graalpython.git
          git remote -v
          git config --global user.name "Retagger Workflow" 
          git config --global user.email "Retagger_Workflow@oracle.com"
          git branch
          git checkout -b weekly_retagger_${{ github.run_id }}
          echo "new text" >> new_file.txt
          git add -A
          git commit -m "Weekly retags"
          git push --set-upstream origin weekly_retagger_${{ github.run_id }}
          gh pr create -B master -d --title "TEST: Merge Weekly Retags" --fill
