name: Test
on:
  workflow_dispatch:

jobs:
  edit:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps: &buildsteps

      - name: Actions/Checkout
        uses: actions/checkout@main

      - name: test and debugs
        run: |
          ls -la
          pwd
          gh --version
          git branch
          git checkout -b weelky_retagger
          echo "new text" >> new_file.txt
          git add -A
          git commit -m "Weekly retags"
          git push weelky_retagger
          gh pr create --B master -d --title "TEST: Merge Weekly Retags"
