name: Test
on:
  workflow_dispatch:

jobs:
  edit:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps: &buildsteps

      - name: Actions/Checkout
        uses: actions/checkout@main

      - name: test and debugs
        run: |
          ls -la
          pwd
          gh --version
          git branch
